import { LoaderCircle, LockKeyhole, LogOut } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BrandLogo } from "@/components/marketing";

export default function AdminLeads() {
  const { isAuthenticated, loading, user, logout } = useAuth({ redirectOnUnauthenticated: true });
  const leads = trpc.leads.list.useQuery(undefined, { enabled: isAuthenticated });
  if (loading || !isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#111111] text-white"><div className="flex items-center gap-3 text-sm text-white/65"><LoaderCircle className="size-5 animate-spin text-[#ff7a00]" /> Verificando acesso seguro…</div></main>;
  return <main className="min-h-screen bg-[#111111] px-4 py-7 text-white"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-5 border-b border-white/10 pb-6"><BrandLogo compact /><div className="flex items-center gap-3"><span className="hidden text-sm text-white/55 sm:inline">{user?.name || "Administrador"}</span><button type="button" onClick={() => logout()} className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-xs font-bold hover:border-[#ff7a00]"><LogOut className="size-4" /> Sair</button></div></header><section className="pt-10"><div className="flex items-start gap-4"><span className="grid size-11 place-items-center rounded-xl bg-[#ff7a00] text-[#171717]"><LockKeyhole className="size-5" /></span><div><h1 className="font-display text-4xl font-black uppercase">Interesses de franquia</h1><p className="mt-1 text-sm text-white/55">Área protegida: os dados não são disponibilizados nas rotas públicas.</p></div></div>{leads.isLoading && <p className="mt-10 text-white/60">Carregando leads…</p>}{leads.error && <p className="mt-10 rounded-xl bg-red-500/15 p-4 text-sm text-red-200">{leads.error.message}</p>}{leads.data && <div className="mt-8 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-white/[.06] text-xs uppercase tracking-wider text-white/55"><tr><th className="px-5 py-4">Contato</th><th className="px-5 py-4">Cidade</th><th className="px-5 py-4">Interesse</th><th className="px-5 py-4">Mensagem</th><th className="px-5 py-4">Data</th></tr></thead><tbody>{leads.data.map(lead => <tr key={lead.id} className="border-t border-white/10"><td className="px-5 py-4"><p className="font-bold">{lead.fullName}</p><a href={`mailto:${lead.email}`} className="text-[#ff9a42]">{lead.email}</a><p className="text-white/55">{lead.phone}</p></td><td className="px-5 py-4">{lead.city}/{lead.state}</td><td className="px-5 py-4">{lead.preferredModel}<br /><span className="text-white/55">{lead.investmentRange}</span></td><td className="max-w-xs px-5 py-4 text-white/65">{lead.message || "—"}</td><td className="px-5 py-4 text-white/55">{new Date(lead.createdAt).toLocaleDateString("pt-BR")}</td></tr>)}</tbody></table></div>}</section></div></main>;
}
