import { ChartNoAxesCombined, ChevronRight, CircleGauge, MapPinned, Medal, ReceiptText, Smartphone, Sparkles, Trophy } from "lucide-react";
import { Link } from "wouter";
import { CustomerAppDownloads } from "@/components/CustomerAppDownloads";
import { Eyebrow, JsonLd, PageShell } from "@/components/marketing";

const appTopics = [
  { icon: ReceiptText, title: "Meu consumo", text: "Acompanhe os registros de consumação vinculados ao seu perfil quando o aplicativo estiver disponível." },
  { icon: Sparkles, title: "Pontos por consumação", text: "Visualize a evolução da sua pontuação e as oportunidades do programa de fidelidade." },
  { icon: Trophy, title: "Ranking da comunidade", text: "Participe de desafios e acompanhe sua posição no ranking quando houver campanha ativa." },
  { icon: MapPinned, title: "Unidades Chopp ON", text: "Encontre os pontos da marca e tenha uma visão rápida da presença da Chopp ON." },
];

export default function CustomerApp() {
  return <PageShell><JsonLd data={{ "@context": "https://schema.org", "@type": "MobileApplication", name: "Aplicativo Chopp ON", applicationCategory: "LifestyleApplication", operatingSystem: "Android, iOS", url: "https://www.choppon24h.com.br/aplicativo", description: "Visão institucional do aplicativo do cliente Chopp ON." }} />
    <main>
      <section className="relative isolate overflow-hidden bg-[#111111] py-16 sm:py-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_76%_18%,rgba(255,122,0,.35),transparent_25%),radial-gradient(circle_at_13%_82%,rgba(255,122,0,.12),transparent_28%)]" /><div className="container grid items-center gap-10 lg:grid-cols-[1fr_.9fr]"><div><Eyebrow>Aplicativo Chopp ON</Eyebrow><h1 className="max-w-3xl font-display text-5xl font-black uppercase leading-[.86] tracking-[-.035em] sm:text-7xl">A sua experiência Chopp ON, <span className="text-[#ff7a00]">sempre por perto.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/68 sm:text-lg">Um espaço pensado para o cliente acompanhar consumo, pontuação, ranking e as unidades da Chopp ON. Os recursos serão liberados em uma próxima fase.</p><div className="mt-8"><CustomerAppDownloads source="customer_app_hero" /></div></div><div className="relative mx-auto grid h-[430px] w-[276px] place-items-center rounded-[3.4rem] border-[10px] border-[#303030] bg-[#080808] shadow-[0_30px_70px_rgba(0,0,0,.46)]"><div className="absolute top-3 h-5 w-24 rounded-full bg-[#222]" /><div className="w-[212px] rounded-[2.25rem] bg-[radial-gradient(circle_at_24%_13%,#4d2a0b,#1d120a_42%,#080808_78%)] p-5"><div className="flex items-center justify-between text-[10px] font-bold text-white/60"><span>Chopp ON</span><Smartphone className="size-4" /></div><div className="mt-7 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#ff9a42]">Minha experiência</p><p className="mt-1 font-display text-3xl font-black uppercase leading-none">Em breve</p></div><span className="grid size-10 place-items-center rounded-xl bg-[#ff7a00] text-[#171717]"><Sparkles className="size-5" /></span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/[.08] p-3"><p className="text-[9px] font-bold uppercase text-white/45">Consumo</p><p className="mt-4 font-display text-2xl font-black">—</p><p className="text-[9px] text-white/45">registrado</p></div><div className="rounded-xl bg-white/[.08] p-3"><p className="text-[9px] font-bold uppercase text-white/45">Pontos</p><p className="mt-4 font-display text-2xl font-black text-[#ff8b27]">—</p><p className="text-[9px] text-white/45">acumulados</p></div></div><div className="mt-4 rounded-xl border border-white/10 bg-white/[.05] p-3"><div className="flex items-center gap-2"><Medal className="size-4 text-[#ff7a00]" /><p className="text-[10px] font-extrabold uppercase">Ranking da comunidade</p></div><p className="mt-2 text-[10px] leading-4 text-white/55">Sua posição aparecerá aqui quando a campanha estiver ativa.</p></div></div></div></div></section>
      <section className="bg-[#f5f0e8] py-18 text-[#171717] sm:py-24"><div className="container"><Eyebrow>Um aplicativo para curtir mais</Eyebrow><div className="grid gap-5 lg:grid-cols-4">{appTopics.map(topic => <article key={topic.title} className="rounded-[1.8rem] border border-black/10 bg-white p-6 shadow-[0_16px_35px_rgba(27,22,18,.08)]"><topic.icon className="size-8 text-[#f26b00]" /><h2 className="mt-10 font-display text-3xl font-black uppercase leading-none">{topic.title}</h2><p className="mt-4 text-sm leading-6 text-black/62">{topic.text}</p></article>)}</div></div></section>
      <section className="bg-[#171717] py-18 sm:py-24"><div className="container grid gap-8 lg:grid-cols-[.88fr_1.12fr]"><div><Eyebrow>Fidelidade e comunidade</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.88] text-white">Consuma, acompanhe e entre no <span className="text-[#ff7a00]">jogo.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-white/60">A visão da plataforma do cliente reúne consumação, pontos e ranking sem complicar a experiência. Esta é uma demonstração da jornada, ainda sem saldos e campanhas reais.</p><div className="mt-8"><CustomerAppDownloads source="customer_app_loyalty" /></div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#ff9a42]">Ranking Chopp ON</p><p className="mt-2 font-display text-4xl font-black uppercase">Sua comunidade</p></div><ChartNoAxesCombined className="size-8 text-[#ff7a00]" /></div><div className="mt-8 space-y-3">{["Posição", "Pontuação", "Próxima conquista"].map((label, index) => <div key={label} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/20 px-4 py-4"><span className="text-sm font-bold text-white/78">{label}</span><span className="font-display text-2xl font-black text-[#ff8b27]">{index === 2 ? "EM BREVE" : "—"}</span></div>)}</div><p className="mt-5 text-xs leading-5 text-white/45">As posições, pontos e conquistas serão atualizados no aplicativo quando o programa estiver disponível.</p></div></div></section>
      <section className="bg-[#111111] py-18 sm:py-24"><div className="container grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><Eyebrow>Unidades Chopp ON</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.88] text-white">Encontre a próxima experiência <span className="text-[#ff7a00]">perto de você.</span></h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/60">O aplicativo reunirá as unidades da marca em um único lugar. Enquanto isso, conheça a presença atual da Chopp ON em Minas Gerais.</p></div><Link href="/#unidades" className="inline-flex w-fit items-center gap-2 rounded-full bg-[#ff7a00] px-5 py-3 text-sm font-extrabold text-[#171717] hover:bg-[#ff922d]">Ver unidades <ChevronRight className="size-4" /></Link></div></section>
    </main>
  </PageShell>;
}
