import { ArrowRight, CalendarDays, ChevronDown, MapPin, PartyPopper, Snowflake } from "lucide-react";
import { useState } from "react";
import { BarrelCalculator } from "@/components/BarrelCalculator";
import { Eyebrow, JsonLd, PageShell, WhatsAppLink } from "@/components/marketing";

const products = [
  ["Pilsen", "Leve, refrescante e versátil para encontros e celebrações.", "Barris de 30L e 50L"],
  ["Chopp de vinho", "Uma alternativa para variar a mesa e surpreender os convidados.", "Consulte disponibilidade e volume"],
  ["Caipirinha", "Opção para eventos que pedem uma experiência diferente.", "Consulte disponibilidade e volume"],
];
const faqs = [
  ["Quais regiões são atendidas?", "A Chopp ON atende Jaboticatubas, Serra do Cipó e Baldim. Para outras localidades, consulte a possibilidade no WhatsApp."],
  ["Qual volume escolher para a festa?", "Use a calculadora como ponto de partida. Duração do evento, perfil dos convidados e outras bebidas podem mudar a melhor indicação."],
  ["O que preciso informar no pedido?", "Data, local, quantidade estimada de pessoas, horário e o tipo de encontro ajudam a orientar o atendimento."],
  ["Posso pedir para eventos corporativos ou celebrações?", "Sim. Informe o contexto do evento pelo WhatsApp para receber a orientação mais adequada."],
];

export default function Delivery() {
  const [openFaq, setOpenFaq] = useState(0);
  return <PageShell><JsonLd data={{ "@context": "https://schema.org", "@type": "FoodEstablishment", name: "Chopp ON Delivery", url: "https://www.choppon24h.com.br/delivery", telephone: "+55 11 99174-8555", areaServed: ["Jaboticatubas, MG", "Serra do Cipó, MG", "Baldim, MG"], sameAs: ["https://www.instagram.com/choppon24h.oficial"] }} />
    <main><section className="relative isolate overflow-hidden bg-[#121212] py-16 sm:py-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_82%_18%,rgba(255,122,0,.4),transparent_20%),linear-gradient(115deg,#101010_10%,#1b140f_70%,#111)]" /><div className="container grid items-center gap-10 lg:grid-cols-[1.12fr_.88fr]"><div><Eyebrow>Chopp delivery</Eyebrow><h1 className="max-w-3xl font-display text-5xl font-black uppercase leading-[.88] tracking-[-.035em] sm:text-7xl">Sua festa merece chopp <span className="text-[#ff7a00]">bem servido.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/68 sm:text-lg">Barril, experiência e atendimento para transformar encontros em boas histórias — com orientação de quem entende de chopp.</p><div className="mt-8 flex flex-wrap gap-3"><WhatsAppLink source="delivery_hero" label="Pedir pelo WhatsApp" /><a href="#calculadora" className="inline-flex items-center gap-2 rounded-full border border-white/20 px-5 py-3.5 text-sm font-extrabold text-white hover:border-[#ff7a00] hover:text-[#ff8b27]">Calcular barris <ArrowRight className="size-4" /></a></div><div className="mt-9 flex flex-wrap gap-2 text-xs font-bold text-white/65"><span className="rounded-full border border-white/15 px-3 py-2">Jaboticatubas</span><span className="rounded-full border border-white/15 px-3 py-2">Serra do Cipó</span><span className="rounded-full border border-white/15 px-3 py-2">Baldim</span></div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.055] p-6"><Snowflake className="size-8 text-[#ff7a00]" /><p className="mt-14 font-display text-4xl font-black uppercase leading-none">Chopp é presença.</p><p className="mt-4 text-sm leading-6 text-white/60">Em um churrasco, aniversário, casamento ou encontro na serra, o que importa é servir bem e aproveitar junto.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#ff7a00] p-4 text-[#191919]"><PartyPopper className="size-5" /><p className="mt-8 font-display text-2xl font-black uppercase leading-none">Festa<br />completa</p></div><div className="rounded-2xl border border-white/10 bg-[#171717] p-4"><CalendarDays className="size-5 text-[#ff7a00]" /><p className="mt-8 font-display text-2xl font-black uppercase leading-none">Eventos<br />especiais</p></div></div></div></div></section>
      <section className="bg-[#f5f0e8] py-18 text-[#171717] sm:py-24"><div className="container"><Eyebrow>Opções para celebrar</Eyebrow><div className="grid gap-5 lg:grid-cols-3">{products.map(([name, text, volume], index) => <article key={name} className="relative overflow-hidden rounded-[1.8rem] border border-black/10 bg-white p-7"><span className="font-display text-7xl font-black text-[#f5f0e8]">0{index + 1}</span><h2 className="relative -mt-6 font-display text-4xl font-black uppercase">{name}</h2><p className="mt-4 max-w-xs text-sm leading-6 text-black/62">{text}</p><p className="mt-5 inline-flex rounded-full bg-[#fff0df] px-3 py-2 text-xs font-extrabold text-[#b84d00]">{volume}</p><div className="mt-5"><WhatsAppLink source={`delivery_product_${index + 1}`} label="Consultar disponibilidade" /></div></article>)}</div></div></section>
      <section id="calculadora" className="scroll-mt-24 bg-[#171717] py-18 sm:py-24"><div className="container grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><Eyebrow>Planeje melhor</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.9] text-white">Quanto chopp cabe no seu <span className="text-[#ff7a00]">momento?</span></h2><p className="mt-5 max-w-sm text-sm leading-7 text-white/60">Uma calculadora rápida para ajudar no primeiro passo. Depois, o atendimento confirma a melhor opção para sua celebração.</p></div><BarrelCalculator /></div></section>
      <section className="bg-[#111111] py-18 sm:py-24"><div className="container grid gap-8 lg:grid-cols-2"><article className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7"><MapPin className="size-8 text-[#ff7a00]" /><Eyebrow>Área atendida</Eyebrow><h2 className="font-display text-4xl font-black uppercase leading-none">Onde a Chopp ON chega</h2><p className="mt-5 text-sm leading-7 text-white/60">Atendimento para Jaboticatubas, Serra do Cipó e Baldim. Para conferir uma localidade próxima ou a logística para seu evento, fale com a equipe.</p><div className="mt-6 flex flex-wrap gap-2">{["Jaboticatubas", "Serra do Cipó", "Baldim"].map(area => <span key={area} className="rounded-full border border-[#ff7a00]/35 px-3 py-2 text-xs font-bold text-[#ff9a42]">{area}</span>)}</div></article><article className="rounded-[2rem] bg-[#ff7a00] p-7 text-[#171717]"><PartyPopper className="size-8" /><p className="mt-14 font-display text-4xl font-black uppercase leading-none">Pedido com orientação humana.</p><p className="mt-5 max-w-md text-sm leading-7 text-[#171717]/75">Mande data, local, convidados e o tipo de evento. A conversa no WhatsApp ajuda a definir o melhor caminho para o pedido.</p><div className="mt-7"><WhatsAppLink source="delivery_service_area" label="Falar sobre meu evento" /></div></article></div></section>
      <section className="bg-[#f5f0e8] py-18 text-[#171717] sm:py-24"><div className="container max-w-4xl"><Eyebrow>Perguntas frequentes</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.9]">Tudo o que você precisa saber antes de pedir.</h2><div className="mt-10 space-y-3">{faqs.map(([question, answer], index) => <article key={question} className="overflow-hidden rounded-2xl border border-black/10 bg-white"><button type="button" onClick={() => setOpenFaq(openFaq === index ? -1 : index)} className="flex w-full items-center justify-between gap-6 px-5 py-5 text-left font-display text-xl font-bold uppercase"><span>{question}</span><ChevronDown className={`size-5 shrink-0 transition-transform ${openFaq === index ? "rotate-180" : ""}`} /></button>{openFaq === index && <p className="border-t border-black/10 px-5 py-5 text-sm leading-7 text-black/64">{answer}</p>}</article>)}</div></div></section>
    </main>
  </PageShell>;
}
