import { ArrowRight, BellRing, ChartNoAxesCombined, CircleAlert, Gauge, MapPin, MonitorSmartphone, PackageCheck, Watch } from "lucide-react";
import { Eyebrow, JsonLd, PageShell } from "@/components/marketing";

const managementTopics = [
  { icon: ChartNoAxesCombined, title: "Sistema de gestão", text: "Visão organizada para acompanhar sua operação, indicadores e decisões importantes." },
  { icon: Gauge, title: "Controle de onde estiver", text: "Uma experiência pensada para consultar o que importa pelo celular, sem depender do balcão." },
  { icon: PackageCheck, title: "Estoque conectado", text: "Sinais de reposição e acompanhamento de barris como apoio para a rotina da unidade." },
];

export default function FranchisePortal() {
  return <PageShell><JsonLd data={{ "@context": "https://schema.org", "@type": "WebPage", name: "Área do Franqueado Chopp ON", url: "https://www.choppon24h.com.br/franqueado", description: "Visão institucional da operação conectada Chopp ON." }} />
    <main>
      <section className="relative isolate overflow-hidden bg-[#111111] py-16 sm:py-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_20%,rgba(255,122,0,.34),transparent_24%),radial-gradient(circle_at_22%_78%,rgba(255,122,0,.13),transparent_26%)]" /><div className="container grid items-center gap-10 lg:grid-cols-[1fr_.9fr]"><div><Eyebrow>Área do franqueado</Eyebrow><h1 className="max-w-3xl font-display text-5xl font-black uppercase leading-[.86] tracking-[-.035em] sm:text-7xl">Uma operação conectada, <span className="text-[#ff7a00]">mais perto de você.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/66 sm:text-lg">A visão de gestão da Chopp ON foi pensada para dar mais autonomia ao franqueado — acompanhando a unidade, os barris e os alertas importantes de onde estiver.</p><p className="mt-5 inline-flex rounded-full border border-[#ff7a00]/35 bg-[#ff7a00]/10 px-4 py-2 text-xs font-bold text-[#ff9a42]">Plataforma em desenvolvimento para as unidades</p></div><div className="relative mx-auto w-full max-w-md rounded-[2.4rem] border border-white/10 bg-[#1a1a1a] p-5 shadow-[0_24px_70px_rgba(0,0,0,.34)]"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#ff7a00] text-[#171717]"><MonitorSmartphone className="size-5" /></span><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#ff9a42]">Chopp ON</p><p className="font-display text-2xl font-bold uppercase">Visão da unidade</p></div></div><span className="rounded-full bg-[#25D366]/15 px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-[#63f49b]">Conectada</span></div><div className="mt-6 grid grid-cols-3 gap-3"><div className="rounded-xl bg-white/[.06] p-3"><p className="text-[10px] font-bold uppercase text-white/45">Vendas</p><p className="mt-3 font-display text-2xl font-black">—</p><p className="text-[10px] text-white/45">no aplicativo</p></div><div className="rounded-xl bg-white/[.06] p-3"><p className="text-[10px] font-bold uppercase text-white/45">Barris</p><p className="mt-3 font-display text-2xl font-black">—</p><p className="text-[10px] text-white/45">monitorados</p></div><div className="rounded-xl bg-white/[.06] p-3"><p className="text-[10px] font-bold uppercase text-white/45">Alertas</p><p className="mt-3 font-display text-2xl font-black text-[#ff8b27]">1</p><p className="text-[10px] text-white/45">demonstração</p></div></div><div className="mt-4 rounded-2xl border border-[#ff7a00]/30 bg-[#ff7a00]/10 p-4"><div className="flex items-center gap-3"><CircleAlert className="size-5 text-[#ff8b27]" /><div><p className="text-xs font-extrabold">BARRIL PRÓXIMO DO FIM</p><p className="mt-1 text-xs text-white/60">Visual de alerta para demonstrar o acompanhamento de estoque.</p></div></div></div></div></div></section>
      <section className="bg-[#f5f0e8] py-18 text-[#171717] sm:py-24"><div className="container grid gap-10 lg:grid-cols-[.82fr_1.18fr]"><div><Eyebrow>Gestão da franquia</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.88]">A operação da sua unidade, em uma visão só.</h2><p className="mt-5 max-w-md text-sm leading-7 text-black/62">A Área do Franqueado concentra a visão institucional de gestão, controle remoto e alertas operacionais para a rede Chopp ON.</p></div><div className="rounded-[2rem] bg-[#171717] p-6 text-white sm:p-8"><p className="font-display text-3xl font-black uppercase">Tópicos de gestão, em frentes independentes.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{managementTopics.map(topic => <article key={topic.title} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><topic.icon className="size-6 text-[#ff7a00]" /><h3 className="mt-8 font-display text-2xl font-black uppercase leading-none">{topic.title}</h3><p className="mt-3 text-xs leading-6 text-white/60">{topic.text}</p></article>)}</div></div></div></section>
      <section className="bg-[#151515] py-18 sm:py-24"><div className="container grid items-center gap-10 lg:grid-cols-[1fr_.85fr]"><div><Eyebrow>Controle remoto</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.88] text-white">Gestão para acompanhar o que importa, <span className="text-[#ff7a00]">onde você estiver.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/62">A proposta visual mostra como a plataforma da franquia pode reunir visão da unidade, alertas de operação e acompanhamento de estoque em uma mesma rotina.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><MapPin className="size-6 text-[#ff7a00]" /><p className="mt-8 font-display text-2xl font-black uppercase">Unidades no mapa</p><p className="mt-3 text-sm leading-6 text-white/55">Visão organizada para acompanhar as operações da rede.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><BellRing className="size-6 text-[#ff7a00]" /><p className="mt-8 font-display text-2xl font-black uppercase">Alertas relevantes</p><p className="mt-3 text-sm leading-6 text-white/55">Notificações de atenção para apoiar decisões no ritmo da operação.</p></div></div></div><div className="relative mx-auto grid h-[360px] w-[252px] place-items-center rounded-[3.2rem] border-[10px] border-[#303030] bg-[#070707] shadow-[0_30px_65px_rgba(0,0,0,.45)]"><div className="absolute top-3 h-5 w-20 rounded-full bg-[#202020]" /><div className="w-[195px] rounded-[2.2rem] bg-[radial-gradient(circle_at_20%_15%,#4a2b0c,#1a120a_40%,#080808_78%)] p-5"><div className="flex items-center justify-between text-[10px] font-bold text-white/55"><span>10:42</span><Watch className="size-4" /></div><div className="mt-8 grid size-12 place-items-center rounded-2xl bg-[#ff7a00] text-[#171717]"><BellRing className="size-6" /></div><p className="mt-6 text-[10px] font-extrabold uppercase tracking-[.16em] text-[#ff9a42]">Alerta Chopp ON</p><p className="mt-2 font-display text-3xl font-black uppercase leading-[.85]">Barril<br />acabando</p><div className="mt-6 rounded-xl bg-white/10 p-3"><p className="text-xs font-bold">Pilsen · unidade</p><p className="mt-1 text-[11px] text-white/55">Nível baixo detectado</p></div><button type="button" className="mt-5 w-full rounded-xl bg-[#ff7a00] px-3 py-2 text-xs font-extrabold text-[#171717]">Abrir na plataforma</button></div></div></div></section>
      <section className="bg-[#ff7a00] py-14 text-[#171717]"><div className="container flex flex-col justify-between gap-7 sm:flex-row sm:items-center"><div><p className="font-display text-4xl font-black uppercase leading-none">A tecnologia acompanha a experiência.</p><p className="mt-3 max-w-xl text-sm leading-6 text-[#171717]/72">Esta área apresenta os recursos em desenvolvimento para a operação do franqueado Chopp ON.</p></div><a href="/franquia" className="inline-flex w-fit items-center gap-2 rounded-full bg-[#171717] px-5 py-3 text-sm font-extrabold text-white hover:bg-black">Conhecer franquias <ArrowRight className="size-4" /></a></div></section>
    </main>
  </PageShell>;
}
