import { ArrowRight, Boxes, CheckCircle2, CircleDollarSign, Gauge, MapPinned, MonitorCog, ShieldCheck, Sparkles } from "lucide-react";
import { FranchiseLeadForm } from "@/components/FranchiseLeadForm";
import { Eyebrow, JsonLd, PageShell } from "@/components/marketing";

const models = [
  { icon: MonitorCog, title: "SMART CHOPP", text: "Estação de autosserviço desenhada para pontos de fluxo, com presença de marca e experiência direta para o cliente." },
  { icon: Boxes, title: "Loja Chopp ON", text: "Formato de operação para quem quer criar um ponto de encontro em torno de uma experiência de chopp bem servida." },
  { icon: Gauge, title: "Operação conectada", text: "Uma jornada pensada para organizar atendimento, consumo e acompanhamento do negócio com mais clareza." },
];

const stages = [
  ["01", "Conversa de cenário", "Entendemos perfil, cidade e momento de negócio antes de indicar um caminho."],
  ["02", "Modelo e ponto", "Alinhamos o formato mais adequado e os critérios para avaliar a oportunidade."],
  ["03", "Implantação", "Planejamento da estrutura, identidade, treinamento e preparação da operação."],
  ["04", "Abertura e suporte", "Acompanhamento da entrada em operação e conexão com a rede Chopp ON."],
];

export default function Franchise() {
  return <PageShell><JsonLd data={{ "@context": "https://schema.org", "@type": "Organization", name: "Chopp ON", url: "https://www.choppon24h.com.br/franquia", logo: "https://www.choppon24h.com.br/manus-storage/chopp-on-logo_ee1c339e.png", sameAs: ["https://www.instagram.com/choppon24h.oficial"] }} />
    <main>
      <section className="relative isolate overflow-hidden border-b border-white/10 bg-[#121212] py-16 sm:py-24"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_82%_18%,rgba(255,122,0,.32),transparent_24%),radial-gradient(circle_at_10%_80%,rgba(255,122,0,.12),transparent_25%)]" /><div className="container grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><Eyebrow>Franquias Chopp ON</Eyebrow><h1 className="max-w-3xl font-display text-5xl font-black uppercase leading-[.88] tracking-[-.035em] text-white sm:text-7xl">Uma experiência de chopp que pode virar <span className="text-[#ff7a00]">seu próximo negócio.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/68 sm:text-lg">A Chopp ON conecta marca, operação e experiência para quem quer levar o universo do chopp a novos pontos de encontro.</p><a href="#cadastro" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#ff7a00] px-6 py-4 text-sm font-extrabold text-[#151515] transition hover:bg-[#ff922d] active:scale-[.97]">Quero conhecer a franquia <ArrowRight className="size-4" /></a></div><div className="relative rounded-[2.2rem] border border-white/10 bg-white/[.055] p-6 sm:p-8"><p className="font-display text-xl font-bold uppercase text-[#ff8b27]">SMART CHOPP</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#ff7a00] p-5 text-[#171717]"><Sparkles className="size-6" /><p className="mt-10 font-display text-3xl font-black uppercase leading-none">Marca<br />presente</p></div><div className="rounded-2xl border border-white/10 bg-[#191919] p-5"><ShieldCheck className="size-6 text-[#ff7a00]" /><p className="mt-10 font-display text-3xl font-black uppercase leading-none">Jornada<br />orientada</p></div></div><p className="mt-5 border-t border-white/10 pt-5 text-sm leading-6 text-white/55">A avaliação de disponibilidade, investimento e implantação é feita em conversa com o time comercial.</p></div></div></section>
      <section className="bg-[#f5f0e8] py-18 text-[#171717] sm:py-24"><div className="container"><Eyebrow>Modelos</Eyebrow><div className="grid gap-6 lg:grid-cols-3">{models.map(model => <article key={model.title} className="rounded-[1.8rem] border border-black/10 bg-white p-7 shadow-[0_16px_35px_rgba(27,22,18,.08)]"><model.icon className="size-9 text-[#f26b00]" /><h2 className="mt-10 font-display text-3xl font-black uppercase">{model.title}</h2><p className="mt-4 text-sm leading-6 text-black/62">{model.text}</p></article>)}</div></div></section>
      <section className="bg-[#f5f0e8] pb-18 text-[#171717] sm:pb-24"><div className="container rounded-[2rem] border border-black/10 bg-[#181818] p-7 text-white sm:p-10"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><Eyebrow>Presença que você pode conhecer</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.88]">Marca com pontos de encontro já em operação.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/60">A conversa sobre franquia parte de uma marca que já está presente em Minas Gerais — em Serra do Cipó e Sete Lagoas — e de um processo que apresenta os próximos passos com transparência.</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><MapPinned className="size-6 text-[#ff7a00]" /><p className="mt-9 font-display text-3xl font-black uppercase">Serra do Cipó</p><p className="mt-3 text-sm leading-6 text-white/55">Unidade Chopp ON em Minas Gerais.</p></article><article className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><CheckCircle2 className="size-6 text-[#ff7a00]" /><p className="mt-9 font-display text-3xl font-black uppercase">Sete Lagoas</p><p className="mt-3 text-sm leading-6 text-white/55">Presença da marca em outra cidade mineira.</p></article></div></div></div></section>
      <section className="bg-[#171717] py-18 sm:py-24"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Do interesse à abertura</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.9] text-white">Um processo claro, sem <span className="text-[#ff7a00]">atalhos.</span></h2><p className="mt-5 max-w-sm text-sm leading-6 text-white/60">Cada praça tem particularidades. Por isso, a jornada começa com análise e termina com uma operação preparada para receber pessoas.</p></div><div className="grid gap-3 sm:grid-cols-2">{stages.map(([number, title, text]) => <article key={number} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><p className="font-display text-3xl font-black text-[#ff7a00]">{number}</p><h3 className="mt-7 font-display text-2xl font-bold uppercase">{title}</h3><p className="mt-3 text-sm leading-6 text-white/55">{text}</p></article>)}</div></div></section>
      <section className="bg-[#111111] py-18 sm:py-24"><div className="container grid gap-6 lg:grid-cols-3"><article className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><MapPinned className="size-7 text-[#ff7a00]" /><h2 className="mt-8 font-display text-3xl font-black uppercase">Expansão consciente</h2><p className="mt-3 text-sm leading-6 text-white/60">A análise considera o contexto de cada cidade e o formato que pode fazer sentido para o ponto.</p></article><article className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><CircleDollarSign className="size-7 text-[#ff7a00]" /><h2 className="mt-8 font-display text-3xl font-black uppercase">Conversas transparentes</h2><p className="mt-3 text-sm leading-6 text-white/60">A indicação de investimento e estrutura é tratada em etapa comercial, de acordo com cada projeto.</p></article><article className="rounded-3xl border border-white/10 bg-white/[.04] p-6"><CheckCircle2 className="size-7 text-[#ff7a00]" /><h2 className="mt-8 font-display text-3xl font-black uppercase">Marca para viver</h2><p className="mt-3 text-sm leading-6 text-white/60">A proposta é simples: dar identidade e qualidade a momentos em que pessoas se encontram.</p></article></div></section>
      <section id="cadastro" className="scroll-mt-24 bg-[#101010] py-18 sm:py-24"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Próximo passo</Eyebrow><h2 className="font-display text-5xl font-black uppercase leading-[.9] text-white">Conte sobre seu <span className="text-[#ff7a00]">plano.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-white/60">Preencha os dados essenciais. O cadastro não exige CPF, não expõe seus dados e direciona a conversa para a oportunidade certa.</p><div className="mt-8 space-y-4 text-sm text-white/72"><p className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[#ff7a00]" />Dados armazenados em ambiente protegido.</p><p className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[#ff7a00]" />Contato comercial com base no seu interesse.</p><p className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[#ff7a00]" />Sem promessa genérica de retorno ou faturamento.</p></div></div><FranchiseLeadForm /></div></section>
    </main>
  </PageShell>;
}
