import { Building2, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { Eyebrow, WhatsAppLink } from "@/components/marketing";

const originPillars = [
  ["01", "Experiência", "Criar momentos que aproximam pessoas."],
  ["02", "Autonomia", "Usar tecnologia para simplificar a operação."],
  ["03", "Padronização", "Desenvolver processos replicáveis para diferentes pontos e cidades."],
  ["04", "Escala", "Construir uma marca preparada para crescer de forma responsável."],
];

const franchiseStructure = [
  ["Marca", "Uma identidade visual e comercial construída para ser reconhecida."],
  ["Modelo de negócio", "Formatos diferentes para diferentes oportunidades."],
  ["Tecnologia", "Sistemas e ferramentas para conectar operação, cliente e gestão."],
  ["Processos", "Métodos e padrões para apoiar implantação e operação."],
  ["Marketing", "Materiais e estratégias para fortalecer a presença local."],
  ["Suporte", "Uma estrutura para acompanhar a jornada do franqueado."],
];

const models = [
  ["01", "CHOPPON SMART", "Cabine ou estação autônoma, preparada para diferentes locais."],
  ["02", "CHOPPON SMART COMPACT", "Solução compacta e autônoma para operar em espaços reduzidos."],
  ["03", "CHOPPON STATION", "Ponto autônomo para ambientes e locais de circulação."],
  ["04", "CHOPPON DELIVERY", "Modelo para empreender com delivery de chope e eventos."],
];

const franchiseJourney = ["Implantação", "Treinamento", "Operação", "Marketing", "Tecnologia", "Suporte", "Expansão"];

export function BrandStory() {
  return <>
    <section id="marca" className="relative isolate overflow-hidden bg-[#f5f0e8] py-16 text-[#171717] sm:py-24">
      <div className="absolute -right-28 top-10 -z-10 size-[28rem] rounded-full border-[52px] border-[#ff7a00]/15 sm:size-[38rem]" />
      <div className="container grid items-end gap-10 lg:grid-cols-[1.08fr_.72fr]">
        <div>
          <Eyebrow>A marca</Eyebrow>
          <h2 className="max-w-4xl font-display text-6xl font-black uppercase leading-[.82] tracking-[-.045em] sm:text-8xl">Não é apenas chopp.<br />É uma marca para <span className="text-[#f26b00]">construir negócios.</span></h2>
          <p className="mt-8 max-w-2xl text-base leading-7 text-black/68 sm:text-lg">A Chopp ON nasceu para transformar a experiência de consumir chopp em uma operação moderna, conectada e escalável.</p>
          <p className="mt-4 max-w-2xl text-sm leading-7 text-black/60">Criamos uma marca para quem quer celebrar, empreender e fazer parte de algo que pode crescer muito além de um único ponto.</p>
          <div className="mt-9 flex flex-wrap gap-3"><Link href="/franquia#cadastro" className="inline-flex items-center gap-2 rounded-full bg-[#ff7a00] px-6 py-4 text-sm font-extrabold text-[#171717] transition hover:bg-[#ff922d] active:scale-[.97]">Quero fazer parte <span aria-hidden="true">→</span></Link><Link href="/franquia" className="inline-flex items-center gap-2 rounded-full border border-black/15 px-6 py-4 text-sm font-extrabold text-[#171717] transition hover:border-[#ff7a00] hover:text-[#cf5a00] active:scale-[.97]">Conhecer a franquia <span aria-hidden="true">→</span></Link></div>
        </div>
        <aside className="relative overflow-hidden rounded-[2rem] border border-black/10 bg-[#171717] p-7 text-white shadow-[0_22px_48px_rgba(28,20,12,.16)] sm:p-9">
          <div className="absolute -right-9 -top-16 size-48 rounded-full border-[30px] border-[#ff7a00]/25" />
          <Sparkles className="relative size-8 text-[#ff7a00]" /><p className="relative mt-16 font-display text-5xl font-black uppercase leading-[.83]">Uma marca para celebrar.<br /><span className="text-[#ff7a00]">Um negócio para crescer.</span></p><p className="relative mt-5 max-w-sm text-sm leading-6 text-white/60">Identidade, tecnologia, processos e experiência reunidos para criar valor ao longo do tempo.</p>
          <div className="relative mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10"><div className="bg-[#171717] p-4"><p className="font-display text-2xl font-black uppercase leading-none">Marca</p><p className="mt-2 text-[11px] leading-5 text-white/50">Uma presença que se reconhece.</p></div><div className="bg-[#171717] p-4"><p className="font-display text-2xl font-black uppercase leading-none text-[#ff8b27]">Método</p><p className="mt-2 text-[11px] leading-5 text-white/50">Uma base para evoluir.</p></div></div>
        </aside>
      </div>
    </section>

    <section className="bg-[#111111] py-18 sm:py-24"><div className="container"><div className="grid gap-8 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><Eyebrow>Mais do que equipamento</Eyebrow><h2 className="max-w-4xl font-display text-5xl font-black uppercase leading-[.84] sm:text-7xl">Quando você investe em uma franquia,<br /><span className="text-[#ff7a00]">você investe em uma marca.</span></h2></div><p className="max-w-xl text-sm leading-7 text-white/62">Equipamentos podem ser comprados. Produtos podem ser encontrados. Mas construir uma marca forte exige tempo, padrão, tecnologia, experiência e consistência.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-[1.75rem] border border-white/10 bg-white/10 sm:grid-cols-5"><div className="bg-[#171717] p-5 font-display text-2xl font-black uppercase">Marca</div><div className="bg-[#171717] p-5 font-display text-2xl font-black uppercase text-[#ff8b27]">Método</div><div className="bg-[#171717] p-5 font-display text-2xl font-black uppercase">Tecnologia</div><div className="bg-[#171717] p-5 font-display text-2xl font-black uppercase text-[#ff8b27]">Experiência</div><div className="bg-[#171717] p-5 font-display text-2xl font-black uppercase">Suporte</div></div><p className="mt-7 text-center font-display text-3xl font-black uppercase text-white">É isso que queremos construir com a Chopp ON.</p></div></section>

    <section className="bg-[#f5f0e8] py-18 text-[#171717] sm:py-24"><div className="container"><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Eyebrow>Por que a Chopp ON existe?</Eyebrow><h2 className="max-w-2xl font-display text-5xl font-black uppercase leading-[.86] sm:text-7xl">Por trás de cada chopp, existe <span className="text-[#f26b00]">uma experiência.</span></h2></div><p className="max-w-2xl text-sm leading-7 text-black/62">A Chopp ON foi criada para transformar o jeito como as pessoas consomem chopp e como empreendedores podem operar nesse mercado.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{originPillars.map(([number, title, description]) => <article key={title} className="group min-h-64 rounded-[1.65rem] border border-black/10 bg-white p-6 shadow-[0_13px_30px_rgba(28,20,12,.06)] transition hover:-translate-y-1 hover:border-[#ff7a00]/60"><p className="font-display text-4xl font-black leading-none text-[#f26b00]">{number}</p><h3 className="mt-14 font-display text-3xl font-black uppercase leading-none">{title}</h3><p className="mt-4 text-sm leading-6 text-black/62">{description}</p></article>)}</div></div></section>

    <section className="bg-[#181818] py-18 sm:py-24"><div className="container"><div className="grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><Eyebrow>Estrutura para franquear</Eyebrow><h2 className="max-w-2xl font-display text-5xl font-black uppercase leading-[.84] sm:text-7xl">Você não leva apenas o nome Chopp ON.<br /><span className="text-[#ff7a00]">Você leva uma estrutura.</span></h2></div><p className="max-w-xl text-sm leading-7 text-white/60">Uma identidade e uma base de operação pensadas para dar mais clareza à implantação, à presença local e ao desenvolvimento de cada ponto.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{franchiseStructure.map(([title, description], index) => <article key={title} className="rounded-[1.6rem] border border-white/10 bg-white/[.045] p-6 transition hover:border-[#ff7a00]/70 hover:bg-white/[.07]"><p className="font-display text-3xl font-black text-[#ff8b27]">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-10 font-display text-3xl font-black uppercase leading-none">{title}</h3><p className="mt-4 text-sm leading-6 text-white/58">{description}</p></article>)}</div></div></section>

    <section id="marca-processo" className="bg-white py-18 text-[#171717] sm:py-24"><div className="container grid gap-9 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><Eyebrow>Proteção e propriedade intelectual</Eyebrow><h2 className="max-w-2xl font-display text-5xl font-black uppercase leading-[.84] sm:text-7xl">Uma marca é um <span className="text-[#f26b00]">patrimônio.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-black/64">A Chopp ON está estruturando sua propriedade intelectual desde o início, porque uma marca forte precisa ser construída com visão de longo prazo.</p><a href="#marca-processo" className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-[#c65700] hover:text-[#f26b00]">Ver informações da marca <span aria-hidden="true">→</span></a></div><aside className="rounded-[2rem] border border-black/10 bg-[#f5f0e8] p-7 sm:p-9"><ShieldCheck className="size-9 text-[#f26b00]" /><div className="mt-10 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-4 font-display text-2xl font-black uppercase leading-none">Proteção</div><div className="rounded-2xl bg-white p-4 font-display text-2xl font-black uppercase leading-none text-[#f26b00]">Identidade</div><div className="rounded-2xl bg-white p-4 font-display text-2xl font-black uppercase leading-none text-[#f26b00]">Valor de marca</div><div className="rounded-2xl bg-white p-4 font-display text-2xl font-black uppercase leading-none">Visão longa</div></div><p className="mt-7 text-xs leading-6 text-black/58"><strong className="text-[#171717]">Pedido de registro de marca no INPI.</strong> Processo nº 937670413, referente ao sinal misto “CHOPP ON – Sua melhor experiência em chopp”, depositado em 16/01/2025, classe NCL(12) 43. Processo de registro em andamento.</p><p className="mt-3 text-xs leading-6 text-black/48">Marca e patente são proteções distintas. Esta comunicação não declara concessão definitiva de registro ou patente.</p></aside></div></section>

    <section className="relative isolate overflow-hidden bg-[#ff7a00] py-18 text-[#171717] sm:py-24"><div className="absolute -right-20 -top-28 -z-10 size-[34rem] rounded-full border-[70px] border-white/20" /><div className="container grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><Eyebrow>Nascemos para crescer</Eyebrow><h2 className="max-w-3xl font-display text-6xl font-black uppercase leading-[.82] sm:text-8xl">Construída para hoje.<br />Pensada para <span className="text-white">amanhã.</span></h2><p className="mt-7 max-w-2xl text-sm leading-7 text-[#171717]/72">Cada novo ponto fortalece a presença da Chopp ON. Cada franqueado ajuda a levar a marca para uma nova região. Cada cliente ajuda a construir uma nova experiência.</p></div><aside className="relative overflow-hidden rounded-[2rem] border border-black/15 bg-[#171717] p-7 text-white shadow-[0_20px_40px_rgba(76,32,0,.18)]"><div className="absolute -right-16 -top-14 size-56 rounded-full border-[34px] border-[#ff7a00]/70" /><MapPin className="relative size-8 text-[#ff7a00]" /><p className="relative mt-12 font-display text-5xl font-black uppercase leading-[.82]">Minas Gerais<br /><span className="text-[#ff7a00]">é onde a presença começa.</span></p><div className="relative mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#ff9a42]">Presença atual</p><p className="mt-3 font-display text-3xl font-black uppercase">Serra do Cipó</p></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#ff9a42]">Presença atual</p><p className="mt-3 font-display text-3xl font-black uppercase">Sete Lagoas</p></div></div><p className="relative mt-5 text-xs leading-5 text-white/48">As próximas expansões serão comunicadas conforme novas operações forem confirmadas.</p></aside></div></section>

    <section className="bg-[#f5f0e8] py-18 text-[#171717] sm:py-24"><div className="container"><div className="grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><Eyebrow>Uma marca, diferentes formatos</Eyebrow><h2 className="max-w-2xl font-display text-5xl font-black uppercase leading-[.84] sm:text-7xl">Uma marca.<br />Diferentes formas de <span className="text-[#f26b00]">empreender.</span></h2></div><p className="max-w-xl text-sm leading-7 text-black/62">A Chopp ON organiza formatos para diferentes contextos de operação, espaço e objetivos de negócio.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{models.map(([number, title, description]) => <article key={title} className="group min-h-64 rounded-[1.7rem] border border-black/10 bg-white p-6 shadow-[0_13px_30px_rgba(28,20,12,.06)] transition hover:-translate-y-1 hover:border-[#ff7a00]/65"><p className="font-display text-4xl font-black leading-none text-[#f26b00]">{number}</p><h3 className="mt-14 font-display text-3xl font-black uppercase leading-none">{title}</h3><p className="mt-4 text-sm leading-6 text-black/60">{description}</p></article>)}</div><div className="mt-8"><Link href="/franquia" className="inline-flex items-center gap-2 rounded-full bg-[#171717] px-6 py-4 text-sm font-extrabold text-white transition hover:bg-[#2a2a2a] active:scale-[.97]">Encontre seu modelo <span aria-hidden="true">→</span></Link></div></div></section>

    <section className="bg-white py-18 text-[#171717] sm:py-24"><div className="container"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><Eyebrow>Jornada do franqueado</Eyebrow><h2 className="max-w-2xl font-display text-5xl font-black uppercase leading-[.84] sm:text-7xl">Uma marca forte não deixa o franqueado <span className="text-[#f26b00]">caminhar sozinho.</span></h2></div><p className="max-w-xl text-sm leading-7 text-black/62">Nosso objetivo é construir uma relação de longo prazo com cada franqueado. Seu crescimento também fortalece a marca.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-[1.75rem] border border-black/10 bg-black/10 sm:grid-cols-2 lg:grid-cols-7">{franchiseJourney.map((step, index) => <div key={step} className="min-h-40 bg-[#f7f4ef] p-5"><p className="font-display text-3xl font-black text-[#f26b00]">{String(index + 1).padStart(2, "0")}</p><p className="mt-12 font-display text-2xl font-black uppercase leading-none">{step}</p></div>)}</div></div></section>

    <section className="bg-[#181818] py-18 sm:py-24"><div className="container grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><Eyebrow>Pensado para o futuro</Eyebrow><h2 className="max-w-3xl font-display text-5xl font-black uppercase leading-[.84] sm:text-7xl">Não estamos construindo apenas um negócio.<br /><span className="text-[#ff7a00]">Estamos construindo uma marca.</span></h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/60">A Chopp ON está sendo desenvolvida para integrar experiência, tecnologia, operação, marketing e diferentes modelos de negócio em uma mesma plataforma.</p></div><div className="overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_72%_14%,rgba(255,122,0,.32),transparent_35%),#111] p-7 sm:p-9"><p className="font-display text-4xl font-black uppercase leading-[.85] sm:text-6xl">Chopp <span className="text-[#ff7a00]">+</span><br />Tecnologia <span className="text-[#ff7a00]">+</span><br />Franquia <span className="text-[#ff7a00]">+</span><br />Delivery <span className="text-[#ff7a00]">+</span><br />Experiência</p><div className="mt-10 border-t border-white/10 pt-6 font-display text-5xl font-black uppercase leading-none text-[#ff7a00]">= Chopp ON</div></div></div></section>

    <section className="bg-[#111111] pb-18 sm:pb-24"><div className="container rounded-[2.2rem] border border-white/10 bg-[linear-gradient(120deg,#1b1b1b,#2a1c0d)] p-8 sm:p-12"><Eyebrow>Faça parte da Chopp ON</Eyebrow><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="max-w-4xl font-display text-5xl font-black uppercase leading-[.84] sm:text-7xl">Se você vai investir, invista em algo que possa <span className="text-[#ff7a00]">crescer com você.</span></h2><p className="mt-6 max-w-2xl text-sm leading-7 text-white/60">Um equipamento pode atender uma demanda hoje. Uma marca forte pode abrir portas amanhã. Por isso, estamos construindo a Chopp ON pensando no longo prazo.</p><p className="mt-6 font-display text-3xl font-black uppercase leading-none text-white">Você investe no seu negócio.<br /><span className="text-[#ff7a00]">Nós construímos a marca junto com você.</span></p></div><div className="flex flex-col gap-3"><Link href="/franquia#cadastro" className="rounded-full bg-[#ff7a00] px-6 py-4 text-center text-sm font-extrabold text-[#171717] transition hover:bg-[#ff922d] active:scale-[.97]">Quero ser franqueado</Link><Link href="/franquia" className="rounded-full border border-white/20 px-6 py-4 text-center text-sm font-extrabold text-white transition hover:border-[#ff7a00] hover:text-[#ff8b27] active:scale-[.97]">Conhecer os modelos</Link><WhatsAppLink source="brand_story_final" label="Falar com o time comercial" /></div></div></div></section>
  </>;
}
